// <auto-generated />
using System;
using GameCollectionAPI_DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCollectionAPI_DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240109024013_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.HasKey("CategoryId");

                    b.HasIndex("GameId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.DevelopmentCompany", b =>
                {
                    b.Property<long>("DevelopmentCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DevelopmentCompanyId"), 1L, 1);

                    b.Property<string>("DevelopmentCompanyLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevelopmentCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DevelopmentCompanyId");

                    b.ToTable("DevelopmentCompanies");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GameId"), 1L, 1);

                    b.Property<long>("GameDevelopmentCompanyDevelopmentCompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameRank")
                        .HasColumnType("int");

                    b.Property<string>("GameSynopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("GameId");

                    b.HasIndex("GameDevelopmentCompanyDevelopmentCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.GameImage", b =>
                {
                    b.Property<long>("GameImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GameImageId"), 1L, 1);

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("GameImageExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameImageId");

                    b.HasIndex("GameId");

                    b.ToTable("GameImages");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UserPasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("UserPasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("UserRoleRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.Category", b =>
                {
                    b.HasOne("GameCollectionAPI_DAL.Models.Game", null)
                        .WithMany("GameCategory")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.Game", b =>
                {
                    b.HasOne("GameCollectionAPI_DAL.Models.DevelopmentCompany", "GameDevelopmentCompany")
                        .WithMany()
                        .HasForeignKey("GameDevelopmentCompanyDevelopmentCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollectionAPI_DAL.Models.User", null)
                        .WithMany("UserGames")
                        .HasForeignKey("UserId");

                    b.Navigation("GameDevelopmentCompany");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.GameImage", b =>
                {
                    b.HasOne("GameCollectionAPI_DAL.Models.Game", null)
                        .WithMany("GameImages")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.User", b =>
                {
                    b.HasOne("GameCollectionAPI_DAL.Models.Role", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.Game", b =>
                {
                    b.Navigation("GameCategory");

                    b.Navigation("GameImages");
                });

            modelBuilder.Entity("GameCollectionAPI_DAL.Models.User", b =>
                {
                    b.Navigation("UserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
